### ISSUE TITLE
Failure/Error: raise ThreadError, 'queue empty' if @queue.empty?

### ISSUE THREAD

**Issue by dblock** [slack-ruby/slack-ruby-client#198]
Seems like a reproducible, but inconsistent failure in Travis.

```
Failures:
  1) integration test client connected sends message
     Failure/Error: raise ThreadError, 'queue empty' if @queue.empty?
     ThreadError:
       queue empty
     # ./spec/support/queue_with_timeout.rb:29:in `block in pop_with_timeout'
     # ./spec/support/queue_with_timeout.rb:25:in `synchronize'
     # ./spec/support/queue_with_timeout.rb:25:in `pop_with_timeout'
     # ./spec/integration/integration_spec.rb:65:in `wait_for_server'
     # ./spec/integration/integration_spec.rb:76:in `block (2 levels) in <top (required)>'
     # ./spec/integration/integration_spec.rb:6:in `block (3 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.4.0/gems/vcr-4.0.0/lib/vcr.rb:261:in `turned_off'
     # ./spec/integration/integration_spec.rb:6:in `block (2 levels) in <top (required)>'
```

https://travis-ci.org/slack-ruby/slack-ruby-client/jobs/332488852
